# Generated by Django 5.2.3 on 2025-06-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('enable_vaccine_tracking', models.BooleanField(default=False)),
                ('enable_covid_screening', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
